# Generated by Django 5.2.10 on 2026-02-09 10:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Balance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("balance_name", models.CharField(max_length=30)),
                ("cash", models.FloatField()),
                ("daily_change", models.FloatField()),
            ],
        ),
    ]
