# Generated by Django 5.2.10 on 2026-01-26 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=30)),
                ('order_type', models.CharField(choices=[('MARKET', 'Market'), ('LIMIT', 'Limit'), ('STOP_ORDERS', 'Stop_orders')], max_length=20)),
                ('order_date', models.DateField(default=datetime.datetime(2026, 1, 26, 15, 14, 44, 535834, tzinfo=datetime.timezone.utc))),
                ('is_executed', models.BooleanField(default=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.FloatField()),
                ('total_value', models.FloatField()),
            ],
        ),
    ]
