# Generated by Django 6.0.1 on 2026-02-02 14:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"ordering": ["-order_date"]},
        ),
        migrations.AlterField(
            model_name="order",
            name="order_date",
            field=models.DateField(
                default=datetime.datetime(
                    2026, 2, 2, 14, 25, 56, 966314, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
